[package]
name = "magma"
version = "0.0.1"
authors = ["Lepuroid <lepuroid@gmail.com>"]
repository = "https://github.com/Lepuroid/libmagma.git"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
